name: clim680
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blosc=1.21.6=hef167b5_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cartopy=0.23.0=py312hf9745cd_2
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cf_xarray=0.10.9=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - cfgrib=0.9.14.1=pyhd8ed1ab_0
  - cftime=1.6.4=py312hc0a28a1_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312h68727a3_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.6=py312h2ec8cdc_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - eccodes=2.38.0=h8bb6dbc_0
  - esmf=8.6.1=mpi_mpich_h7cf99a1_103
  - esmpy=8.6.1=pyhc1e730c_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - findlibs=0.0.5=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_0
  - flexparser=0.3.1=pyhd8ed1ab_0
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.54.1=py312h66e93f0_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - freexl=2.0.0=h743c826_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.13.0=h5888daf_0
  - geotiff=1.7.3=h77b800c_3
  - giflib=5.2.2=hd590300_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=mpi_mpich_h0f54ddc_5
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - intake=2.0.8=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.27.0=pyh707e725_0
  - jasper=4.2.4=h536e39c_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.4=hfca40fe_0
  - libblas=3.9.0=24_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=24_linux64_openblas
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.21=h4bc722e_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgdal-core=3.9.2=hceee5e3_6
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libglu=9.0.0=ha6d2627_1004
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=24_linux64_openblas
  - libnetcdf=4.9.2=mpi_mpich_h761946e_14
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpnetcdf=1.13.0=mpi_mpich_hdf74816_101
  - libpng=1.6.44=hadc24fc_0
  - librttopo=1.1.0=h97f6797_17
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=h1b4f908_11
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.7.0=h6565414_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzip=1.11.1=hf83b1b0_0
  - libzlib=1.3.1=h4ab18f5_1
  - llvmlite=0.45.0=py312he100287_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h280c20c_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=py312h8a5da7c_0
  - matplotlib-base=3.9.2=py312hd3ec401_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - metpy=1.6.3=pyhd8ed1ab_0
  - minizip=4.0.7=h401b404_0
  - mpi=1.0=mpich
  - mpich=4.2.2=h4a7f18d_101
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf-fortran=4.6.1=mpi_mpich_h2e543cf_6
  - netcdf4=1.7.1=nompi_py312h21d6d8e_102
  - networkx=3.5=pyhe01879c_0
  - numba=0.62.1=py312h907b442_0
  - numpy=2.1.1=py312h58c1407_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312hf9745cd_1
  - parallelio=2.6.3=mpi_mpich_h43d51f9_100
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.44=hc749103_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h56024de_1
  - pint=0.24.3=pyhd8ed1ab_0
  - pip=24.2=pyh8b19718_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - proj=9.5.0=h12925eb_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py312h66e93f0_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyogrio=0.10.0=py312he8b4914_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyproj=3.6.1=py312he630544_10
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.6=hc5c86c4_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-eccodes=2.37.0=py312hc0a28a1_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - pyzmq=26.2.0=py312hbf22597_2
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py312h4f0b9e3_0
  - scipy=1.14.1=py312h7d485d2_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.1.0=pyhd8ed1ab_0
  - shapely=2.0.6=py312h391bc85_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - sparse=0.17.0=pyhcf101f3_0
  - sqlite=3.46.1=h9eae976_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.5=py312h4f23490_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py312h66e93f0_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - tzdata=2024a=h8827d51_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xerces-c=3.2.5=h988505b_2
  - xesmf=0.8.10=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.3=hb9d3cd8_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=ha4adb4c_5
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - bokeh==3.8.0
      - boto3==1.40.53
      - botocore==1.40.53
      - cattrs==25.3.0
      - cloudpickle==3.1.1
      - crc32c==2.7.1.post0
      - dask==2025.10.0
      - distributed==2025.10.0
      - donfig==0.8.1.post1
      - fastprogress==1.0.3
      - frozenlist==1.8.0
      - intake-esm==2025.7.9
      - itables==2.5.2
      - jmespath==1.0.1
      - locket==1.0.0
      - lxml==6.0.2
      - lz4==4.4.4
      - msgpack==1.1.2
      - multidict==6.7.0
      - narwhals==2.8.0
      - numcodecs==0.16.3
      - partd==1.4.2
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - propcache==0.4.1
      - pyarrow==21.0.0
      - pydantic==2.12.2
      - pydantic-core==2.41.4
      - pydap==3.5.8
      - requests-cache==1.2.1
      - s3transfer==0.14.0
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - tblib==3.1.0
      - toolz==1.0.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - url-normalize==2.2.1
      - webob==1.8.9
      - xarray==2025.10.1
      - xyzservices==2025.4.0
      - yarl==1.22.0
      - zarr==3.1.3
      - zict==3.0.0
prefix: /home/tquresh/miniforge/envs/clim680
